# Generated by Django 4.2.2 on 2023-07-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(max_length=255)),
                ('groom_name', models.CharField(max_length=255)),
                ('wedding_date', models.DateTimeField()),
                ('wedding_location', models.CharField(max_length=255)),
                ('wedding_description', models.TextField()),
            ],
        ),
    ]
