# Generated by Django 4.2.2 on 2023-07-11 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='id',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField()),
                ('photo_description', models.CharField(max_length=255)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.wedding')),
            ],
        ),
    ]
